baseURL = 'https://aldenparkproject.netlify.app/'
languageCode = 'en-us'
title = 'Code-A-Thon: AldenPark'
theme = 'PaperMod_nogit'

[params]
description = "A WWII Bletchley Park-inspired code-breaking hackathon at Allegheny College"
author = "DataGators & ACM Club"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
disableThemeToggle = true
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

[params.homeInfoParams]
Title = "âš¡ Code-A-Thon: AldenPark âš¡"
Content = """
**Operation Codebreaker** - A WWII-inspired hackathon where student teams crack encrypted messages using computational methods.

ğŸ“… **Date:** TBA (Saturday Afternoon)  
â±ï¸ **Duration:** 6 Hours  
ğŸ‘¥ **Team Size:** Up to 4 members  
ğŸ **Prizes:** T-shirts & Awards  
ğŸ“ **Location:** Allegheny College

Break codes. Build software. Make history.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"

[menu]
[[menu.main]]
identifier = "home"
name = "ğŸ  Home"
title = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "ğŸ“– About"
title = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "codes"
name = "ğŸ” Codes"
title = "The Codes"
url = "/codes/"
weight = 30

[[menu.main]]
identifier = "breaking"
name = "ğŸ”¨"
title = "Breaking Codes"
url = "/breaking/"
weight = 40

[[menu.main]]
identifier = "rules"
name = "ğŸ“‹ Rules"
title = "Rules & FAQ"
url = "/rules/"
weight = 50

[[menu.main]]
identifier = "tips"
name = "ğŸ’¡ Tips"
title = "Tips"
url = "/tips/"
weight = 55

[[menu.main]]
identifier = "live"
name = "ğŸ’» Programming"
title = "Live Notebooks"
url = "/live/"
weight = 58

[[menu.main]]
identifier = "contact"
name = "ğŸ“ Contact"
title = "Contact"
url = "/contact/"
weight = 60

[[menu.main]]
identifier = "resources"
name = "ğŸ“š Resources"
title = "Resources"
url = "/resources/"
weight = 65

[[menu.main]]
identifier = "posts"
name = "ğŸ“¢ Posts"
title = "News"
url = "/posts/"
weight = 70

[[menu.main]]
identifier = "search"
name = "ğŸ” Search"
title = "Search"
url = "/search/"
weight = 75

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true
